Repository IITC-CE/ingress-intel-total-conversion, pull requests merged in 2019-11, with the labels that each got.

#271 Change processing of plugins metadata to support IITC-Mobile for iOS
  code/boot.js
  code/utils_misc.js
Labels: bug

#270 IITC-Mobile: Fix plugin initialization bug
  mobile/app/src/main/java/org/exarhteam/iitc_mobile/IITC_FileManager.java
Labels: bug, mobile

#265 portals-list: filter out portal without real data (bug in intel)
  plugins/portals-list.user.js
Labels: bug, plugin

#243 API for local files (up|down)loading
  code/smartphone.js
  code/utils_file.js
  plugins/bookmarks.user.js
  plugins/draw-tools.user.js
Labels: core, development, enhancement, plugin

#267 Change default intel url (to match stock)
  code/boot.js
  code/smartphone.js
  code/utils_misc.js
  mobile/app/src/main/AndroidManifest.xml
  mobile/app/src/main/java/org/exarhteam/iitc_mobile/IITC_Mobile.java
  mobile/app/src/main/java/org/exarhteam/iitc_mobile/IITC_WebViewClient.java
  mobile/app/src/main/java/org/exarhteam/iitc_mobile/share/ShareActivity.java
  plugins/draw-tools.user.js
  plugins/sync.user.js
Labels: bug

#278 Update Leaflet to 1.6.0
  external/leaflet-src.js
  external/leaflet.canvas-markers.js
  external/leaflet.css
  external/versions.md
Labels: development

#264 Update docs
  ATTRIBUTION.md
  CHANGES.md
  CONTRIBS.md
  HACKING.md
  Makefile
  README.md
  external/leaflet.draw-geodesic.js
  external/versions.md
  mobile/HACKING.md
  mobile/README.md
  plugins/README.md
Labels: development
